# Site basics
title:       IFT3700-Hockey
tagline:     "A template based on the Minima Jekyll theme"
description: "Hockey project"

# Your GitHub Pages URL and baseurl for *project* sites
url:      "https://tibbyshr.github.io"
baseurl:  "/3700-Hockey-Blog"   

# Posts
permalink: pretty
paginate:  5
paginate_path: "/page:num"

# Theme & plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Minima 的顶部导航
header_pages:
  - index.md
  - tutoriel-telechargement.md
  - about.md

# Author 
author:
  name:  
  email: ""
